# Generated by Django 3.1.2 on 2020-11-18 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery_details',
            options={'verbose_name': 'Deliverie'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
