# Generated by Django 3.1.2 on 2021-01-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_pharmacy', '0003_remove_stock_manufacture_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='delivery_details',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='delivery_details',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_pharmacy.customer', verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='delivery_details',
            name='deliver_addr',
            field=models.CharField(max_length=100, verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='delivery_details',
            name='deliver_date',
            field=models.DateTimeField(null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='delivery_details',
            name='deliver_name',
            field=models.CharField(max_length=20, verbose_name='Receiver Name'),
        ),
        migrations.AlterField(
            model_name='delivery_details',
            name='deliver_phn',
            field=models.CharField(max_length=20, verbose_name='Delivery Phone #'),
        ),
        migrations.AlterField(
            model_name='delivery_details',
            name='deliver_status',
            field=models.CharField(choices=[('pen', 'pending'), ('proc', 'process started'), ('delv', 'on the way')], max_length=4, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='delivery_details',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_pharmacy.order', verbose_name='Delivery ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_items',
            field=models.PositiveSmallIntegerField(verbose_name='Total Items'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_pharmacy.order', verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_pharmacy.products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
