# Generated by Django 3.1.2 on 2021-01-10 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_pharmacy', '0010_auto_20210109_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery_details',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_pharmacy.customer', verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='delivery_details',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_pharmacy.order', verbose_name='Delivery ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_pharmacy.customer'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_pharmacy.order', verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_pharmacy.products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
