# Generated by Django 3.1.2 on 2021-01-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_pharmacy', '0011_auto_20210111_0035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_items',
            new_name='OrderItems',
        ),
    ]
