# Generated by Django 3.1.2 on 2021-01-22 21:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_pharmacy', '0014_auto_20210117_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_details',
            name='deliver_status',
            field=models.CharField(choices=[('pen', 'Pending'), ('proc', 'Processing'), ('delv', 'Delivering'), ('comp', 'Completed')], default='pen', max_length=4, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 2, 6, 41, 236369), verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_pharmacy.order', verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_pharmacy.products', verbose_name='Product'),
        ),
    ]
