# Generated by Django 3.1.2 on 2021-01-23 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_pharmacy', '0016_auto_20210123_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='item_qty',
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 4, 52, 18, 437134), verbose_name='Order Date'),
        ),
    ]
