# Generated by Django 3.1.2 on 2021-03-07 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_pharmacy', '0019_auto_20210306_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prescription_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 11, 41, 17, 98333), verbose_name='Order Date'),
        ),
    ]
