# Generated by Django 3.1.2 on 2021-03-10 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_pharmacy', '0021_auto_20210307_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 9, 43, 53, 607882), verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='prescription_img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
