# Generated by Django 3.1.2 on 2021-03-14 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_pharmacy', '0025_auto_20210314_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_details',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_pharmacy.customer', verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='delivery_details',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_pharmacy.order', verbose_name='Delivery ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 15, 36, 41, 195275), verbose_name='Order Date'),
        ),
    ]
