# Generated by Django 4.0.4 on 2023-04-21 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online_pharmacy', '0026_auto_20210314_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Date'),
        ),
    ]
